modLoader="javafml"
loaderVersion="[35,)"
logoFile="favicon.png"
license="GNU Generic Public License 3"

[[mods]]
    modId="serializableconsciousness"
    version="${version}"
    displayName="Serializable Consciousness"
    authors="Timicasto, Sukazyo, BloCamLimb"
    credits=""
    description='''
        http://timicasto.sukazyo.cc:12000/TeaCon/intro.html
    '''

[[dependencies.serializableconsciousness]]
    modId="forge"
    mandatory=true
    versionRange="[35.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.serializableconsciousness]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4, 1.17)"
    ordering="NONE"
    side="BOTH"
